blog/urls.py
from django.urls import path
from .views import BlogListView, BlogDetailsView

app_name = "blog"

urlpatterns = (
    path("", BlogListView.as_view(), name="blogs_list"),
    path("<str:slug>", BlogDetailsView.as_view(), name="blog_details"),
)

my_cv/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path("", include("resume.urls")),
    path("blog/", include("blog.urls")),
    path('admin/', admin.site.urls),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/partials/footer.html
<footer class="pt-4 pb-4 text-center bg-cover-footer">
  <div class="container">
    <div class="my-3">
      <div class="h4">{{info.name}}</div>
      <p>{{info.spacialization}}</p>
      <div class="social-nav">
        <nav role="navigation">
          <ul class="nav justify-content-center">
            {% if social %}
            {% for acc in social %}
            {% if acc.account == 'fb' %}
            <li class="nav-item"><a class="nav-link" href="{{acc.profile_link}}" title="Facebook"><i
                  class="fab fa-facebook"></i><span class="menu-title sr-only">Facebook</span></a></li>
            {% endif %}
            {% if acc.account == 'ig' %}
            <li class="nav-item"><a class="nav-link" href="{{acc.profile_link}}" title="Instagram"><i
                  class="fab fa-instagram"></i><span class="menu-title sr-only">Instagram</span></a></li>
            {% endif %}
            {% if acc.account == 'in' %}
            <li class="nav-item"><a class="nav-link" href="{{acc.profile_link}}" title="LinkedIn"><i
                  class="fab fa-linkedin"></i><span class="menu-title sr-only">LinkedIn</span></a></li>
            {% endif %}
            {% if acc.account == 'tw' %}
            <li class="nav-item"><a class="nav-link" href="{{acc.profile_link}}" title="Twitter"><i
                  class="fab fa-twitter"></i><span class="menu-title sr-only">Twitter</span></a></li>
            {% endif %}
            {% endfor %}
            {% endif %}
          </ul>
        </nav>
      </div>
    </div>
    <div class="text-small text-secondary">
      <div class="mb-1">{{info.name}}. All rights reserved.</div>
      <div>
      </div>
    </div>
</footer>

templates/partials/header.html
<header class="bg-light">
  <nav class="navbar navbar-expand-lg navbar-light bg-cover" id="header-nav" role="navigation">
    <div class="container">
      <a class="link-dark navbar-brand site-title mb-0" href="javascript:void(0)">{{info.name}}</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span
          class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ms-auto me-2">
          <li class="nav-item"><a class="nav-link" href="#about">About</a></li>
          <li class="nav-item"><a class="nav-link" href="#services">Services</a></li>
          <li class="nav-item"><a class="nav-link" href="#skills">Skills</a></li>
          <li class="nav-item"><a class="nav-link" href="#portfolio">Portfolio</a></li>
          <li class="nav-item"><a class="nav-link" href="#experience">Experience</a></li>
          <li class="nav-item"><a class="nav-link" href="#contact">Contact</a></li>
          <li class="nav-item"><a class="nav-link" href="{% url 'blog:blogs_list' %}">Blog</a></li>
        </ul>
        <input type="checkbox" class="checkbox" id="checkbox">
        <label for="checkbox" class="label">
          <i class="fas fa-moon"></i>
          <i class='fas fa-sun'></i>
          <div class='ball'>
        </label>
      </div>
    </div>
  </nav>
</header>